KapyTest1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KapyTest1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KapyTest1/Controllers/Source1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KapyTest1.Models;

namespace KapyTest1.Controllers
{
    public class Source1Controller : Controller
    {
        private kapymvc1Entities db = new kapymvc1Entities();

        // GET: Source1
        public ActionResult Index()
        {
            return View(db.Source1.ToList());
        }

        // GET: Source1/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source1 source1 = db.Source1.Find(id);
            if (source1 == null)
            {
                return HttpNotFound();
            }
            return View(source1);
        }

        // GET: Source1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Source1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "sourceId,sourceName,sourceUrl")] Source1 source1)
        {
            if (ModelState.IsValid)
            {
                db.Source1.Add(source1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(source1);
        }

        // GET: Source1/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source1 source1 = db.Source1.Find(id);
            if (source1 == null)
            {
                return HttpNotFound();
            }
            return View(source1);
        }

        // POST: Source1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sourceId,sourceName,sourceUrl")] Source1 source1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(source1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(source1);
        }

        // GET: Source1/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source1 source1 = db.Source1.Find(id);
            if (source1 == null)
            {
                return HttpNotFound();
            }
            return View(source1);
        }

        // POST: Source1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Source1 source1 = db.Source1.Find(id);
            db.Source1.Remove(source1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KapyTest1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KapyTest1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KapyTest1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>KAPY News</h1>
    <p class="lead">KAPY news aggregates news from various sources and provides most updated news for you.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("News","Index","News")</h2>
        <p>
            KAPY news aggregates news from various sources and provides most updated news for you.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>@Html.ActionLink("Category", "Index", "Category1")</h2>
        <p>KAPY news has news in various categories.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>@Html.ActionLink("Source", "Index", "Source1")</h2>
        <p>KAPY news collect news from various sourcesB.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>